### ISSUE TITLE
Large error in a specific case

### ISSUE THREAD

**Issue by Ummon** [chraibi/EEOver#1]
With this file above as input named "same_ellipses.txt" : 

```
1   43.28271488 22.83392139 41.94107253 39.78655647 3.120439222 32.64211672 27.84469155 53.92619514 45.62883047 3.093992268
2   32.64211672 27.84469155 53.92619514 45.62883047 3.093992268 43.28271488 22.83392139 41.94107253 39.78655647 3.120439222
```

And the command "./overlap same_ellipses.txt 1" we obtain the following file result (output = TOMS) :

```
# id  areaEllipse1(pi.A.B)  areaEllipse2(pi.A.B)  OverlapAreaAnalytical  OverlapAreaPolynomial  err
1     3104.8803     2855.4239     1659.1595     2216.9863        0.3362
2     2855.4239     3104.8803     2227.3519     2216.9863        0.0047
```

The two ellipses are the same and are just swapped between cases. The computed area given by the function 'ellipse_ellipse_overlap_netlibs' in the first case is ~ 25% below the area computed with polygon approximation which seems very large. Is it a normal approximation error ?

I put the output of 'plot.py' below.

![case000](https://cloud.githubusercontent.com/assets/89829/11931905/95c623e6-a7f1-11e5-8675-5365d936f0a2.png)

![case001](https://cloud.githubusercontent.com/assets/89829/11931904/95c5b938-a7f1-11e5-8e46-820bdbfc0dfc.png)

**Comment by Ummon** [comment]
I create a pull-request to fix this issue: https://github.com/chraibi/EEOver/pull/2

**Comment by chraibi** [comment]
@Ummon thanks! I'll have a look at this in the WE. Indeed it's strange. 
Did you try?

```
./overlap same_ellipses.txt 2
```

Does it behave similarly?

**Comment by Ummon** [comment]
The choice only matters for the function 'ellipse_ellipse_overlap_gsl'. I only tested 'ellipse_ellipse_overlap_netlibs'. But I found the bug and submit a fix as I said above.

**Comment by chraibi** [comment]
@Ummon  You are right. In the [preprint-paper](http://arxiv.org/pdf/1106.3787v1.pdf)
`page 68 line 2961` matches exactly your fix. 
Thanks for that.
